### ISSUE TITLE
Adapt for Polar Robot

### ISSUE THREAD

**Issue by hackintoshlover** [rdudhagra/Sand-Table#29]
Hi,
Thanks for the awesome build.
Quick question,
I have modified marlin firmware to adapt polar co-ordinates.
Is the raspberry pi sand table control software compatible with polar co-ordinates instead of cartesian co-ordinates?
Any steps for how to achieve the same?

**Comment by rdudhagra** [comment]
Hey!
Should be fairly straightforward. You'll need to modify [`website/server/routes/gcode_controller.js`](https://github.com/rdudhagra/Sand-Table/blob/master/Website/server/routes/gcode_controller.js) slightly to send polar coordinate commands in the format that you'll need and possibly [`process_theta_rho.js`](https://github.com/rdudhagra/Sand-Table/blob/master/Website/server/routes/process_theta_rho.js) if you still want to be able to upload `.thr` track files. Good thing is that `.thr` files are already in polar coordinates so the code in this file will end up being much simpler.

Check out #21 for some more info on switching to a polar coordinate system if you haven't seen that thread yet...I can offer more specific guidelines on what you'd need to change if you have more details on how your modified marlin fw accepts polar coordinates/etc.

**Comment by hackintoshlover** [comment]
Hi,
I this for firmware with disabled z-axis.
https://github.com/kory75/Marlin_360

Rest any 3d  printer software works for  control.

**Comment by hackintoshlover** [comment]
Hey Ravi,
Will this software work with h-bot setup instead of core-xy?

**Comment by rdudhagra** [comment]
Seems like Marlin_360 takes XY coordinates as input so if you're fine with a slightly incorrect preview image on the website (square instead of circular) then I don't think you'll need to make any modifications.

I'm not familiar with an H-Bot setup but from a quick google search it seems compatible. Basically anything that Marlin can do (actually anything that can take GCode commands) will work.
