### ISSUE TITLE
Problem with the LEDs

### ISSUE THREAD

**Issue by PDotStrong** [rdudhagra/Sand-Table#39]
Hi thank you so much for your guide. i struggled a lot but I see light at the end ^^ But now I got Errors like this:

[1] chmod: cannot access '/home/pi/arduino-cli': No such file or directory
[1] /home/sandtable/Documents/Sand-Table/Website/flash-light-strip-controller.sh: line 14: /home/pi/arduino-cli: No such file or directory
[1] /home/sandtable/Documents/Sand-Table/Website/flash-light-strip-controller.sh: line 17: /home/pi/arduino-cli: No such file or directory
[1] /home/sandtable/Documents/Sand-Table/Website/flash-light-strip-controller.sh: line 25: /home/pi/arduino-cli: No such file or directory
[1] /home/sandtable/Documents/Sand-Table/Website/flash-light-strip-controller.sh: line 29: /home/pi/arduino-cli: No such file or directory
[1] Server (production) is listening on port 3000

^^

and I cant change the LED to a static light?!?

**Comment by rdudhagra** [comment]
Hmm seems like my LED strip uploading script failed to install `arduino-cli`. 
Two things to try:
1. Can you try running `flash-light-strip-controller.sh` in the `Website` folder manually?
2. Run the following commands to install `arduino-cli` (taken directly from the above script)?
```bash
curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/home/pi/ sh
chmod +x /home/pi/arduino-cli
```

Let me know if it still doesn't work after doing both of those.

**Comment by PDotStrong** [comment]
I tried the first Solution and got:

sandtable@raspberrypi:~/Documents/Sand-Table/Website $ sh flash-light-strip-controller.sh
arduino-cli not found! Installing...
/home/pi/ ($BINDIR) folder not found. Please create it before continuing.
Failed to install arduino-cli
chmod: cannot access '/home/pi/arduino-cli': No such file or directory
flash-light-strip-controller.sh: 14: /home/pi/arduino-cli: not found
flash-light-strip-controller.sh: 17: /home/pi/arduino-cli: not found
flash-light-strip-controller.sh: 22: cd: can't cd to flash-light-strip-controller.sh
flash-light-strip-controller.sh: 25: /home/pi/arduino-cli: not found
flash-light-strip-controller.sh: 28: source: not found
flash-light-strip-controller.sh: 29: /home/pi/arduino-cli: not found
Done!

Second Solution:

sandtable@raspberrypi:~ $ cd ~/Documents/Sand-Table/Website
sandtable@raspberrypi:~/Documents/Sand-Table/Website $ curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/home/pi/ sh
od +x /home/pi/arduino-cli/home/pi/ ($BINDIR) folder not found. Please create it before continuing.
Failed to install arduino-cli
sandtable@raspberrypi:~/Documents/Sand-Table/Website $ chmod +x /home/pi/arduino-cli
chmod: cannot access '/home/pi/arduino-cli': No such file or directory
sandtable@raspberrypi:~/Documents/Sand-Table/Website $

No change =(

**Comment by PDotStrong** [comment]
I tried to create the missing directory but now i got this:

sandtable@raspberrypi:~ $ sudo mkdir /home/pi
sandtable@raspberrypi:~ $ curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/home/pi/ sh
Installing in /home/pi/
ARCH=ARMv7
OS=Linux
Using curl as download tool
Downloading https://downloads.arduino.cc/arduino-cli/arduino-cli_0.31.0_Linux_ARMv7.tar.gz
cp: cannot create regular file '/home/pi/arduino-cli': Permission denied
Failed to install arduino-cli

**Comment by PDotStrong** [comment]
is it possible that I installed everything in wrong directorys? because I find often the path /home/pi/ or /home/pi/Documents... or must I change Pi to my raspberry name like sandtable

**Comment by PDotStrong** [comment]
I solved the problem! Thank you

**Comment by PDotStrong** [comment]
I still have the problem, when I want to fix a static color, I got anything else =/

**Comment by rdudhagra** [comment]
Hmm ok not sure if I fully follow...
If `arduino-cli` is still giving you problems, my guess is it's a permissions issue. So try running:
```bash
sudo chown -R pi:pi /home/pi
sudo chmod -R 755 /home/pi
```
(source: https://forums.raspberrypi.com/viewtopic.php?t=177135)

You shouldn't need to change your Pi's hostname.

**Comment by rdudhagra** [comment]
OOOOH I see what the issue is. Your username is `sandtable`, not `pi`. So my scripts assume the latter username and I guess that broke things. So you could either rename your user or just change all references of `/home/pi` in the code to `/home/sandtable`.

**Comment by rdudhagra** [comment]
The only instances that I can find for the username change are in `flash-light-strip-controller.sh` in the `Website` folder and `start.sh` in the same folder (which I mentioned in #40).

**Comment by PDotStrong** [comment]
Update: I think I find a problem, my Leds strips ar sk6812 and that are rgbw leds and so not direct supported from fastled right? Can you help me?

**Comment by PDotStrong** [comment]
Hi I tried now a rgb led strip but there are also strange thing happen. Is it possible to run my rgbw led strip ? Or i have to use a rgb led strip? I looking for a nice solutions =) that is my last issue before I can finisch the table =S

**Comment by rdudhagra** [comment]
You may have to do some googling but any LED strip that's supported by the `FastLED` Arduino library will work!

**Comment by PDotStrong** [comment]
I find out that my LED RGBW are not supported from FastLED only with a work over, so I bought an LED RGB WS2813 5050 5V with DI/DO Bi/Bo so exact the same like yours?!? But I only get a red flashing light strip =/ I´m almost lost with it... Spend so much time now for no steps further :,(

**Comment by rdudhagra** [comment]
WS2813 should work. Can you send me a video of the LEDs and lots of detailed images of your wiring?

**Comment by PDotStrong** [comment]
Hi I found the problm with the RGB Stripes. i wired the LED Stripes like your circuit diagrams and that was not possible because the Digital Pin of the Arduino and the LED have not the same ground and produced my issues.

**Comment by PDotStrong** [comment]
Hi, I changed the rgbw trough rgb stripes 2 x 1 meter stripes with 60 leds 

set it uo in the arduino and uploaded it and it works, bit when I connect everything raspberry etc the only one strip shine?!? What could be the reason?

**Comment by PDotStrong** [comment]
Hi, I changed the rgbw trough rgb stripes 2 x 1 meter stripes with 60 leds each

set it in the arduino and uploaded it and it works connected only to the arduino and pc, but when I connect everything raspberry etc the only one strip shine?!? What could be the reason?

**Comment by rdudhagra** [comment]
Can you send pictures + a wiring diagram for your setup?

**Comment by PDotStrong** [comment]
I will send you all combination I tried :)
On Monday I will send you everything !

thank you so much for your help! :)
