### ISSUE TITLE
Is it possible to change the design ob the website? like color? or put in a background?

### ISSUE THREAD

**Issue by PDotStrong** [rdudhagra/Sand-Table#41]
I like the Website easy and comfortable. I only want to change the Background to maybe a cool pic. Is this possible? and if yes where i have to look up =)

Sry for all the stupid questions xD but Im very new to arduinos Raspberrys and co

**Comment by rdudhagra** [comment]
Yea this should be possible. You'll have to look up how the React.js framework works but it should theoretically be a simple modification to `Website/src/app/index.jsx`

**Comment by PDotStrong** [comment]
I found how I can change the Text of everything in the app but everything that seems to be color doesnt change anything if I changed the values xD is it really only the index.jsx?

**Comment by rdudhagra** [comment]
Might be another file, possibly one of the `.scss` files.

**Comment by PDotStrong** [comment]
I try it and keep you up to date :)
