### ISSUE TITLE
Drawn Tracks are wrong

### ISSUE THREAD

**Issue by PDotStrong** [rdudhagra/Sand-Table#43]
Next Problem ^^ 

I tried to create own Sand Pics on Sandify.org and put in my machine values (470x510) and when i upload these files in the machine it draw only oin 1/3 of the area =/ but why? I changed the values in .env and marlin and the homing works fine.

also when I use the button fit the pic get bigger but not enough to fill the hole area.

i tried sand pic from thers but these are too big for my area and it crashed in the walls so i tried fit these pic but doesnt work =/

maybe I´m blind but can you help^^ 
How you create your Tracks? Also sandify or something else? The size of the table is changed in .env and marlin and I also sudo daemon-reload to refresh everything? And the homing works .

**Comment by PDotStrong** [comment]
Also you have Track that are bigger then your table size, if I use bigger track from the internet my Carrier crash in the boarders and that are not right or?

**Comment by rdudhagra** [comment]
Are you exporting as `gcode` or `thr`? The polar files' radius values go from 0 to 1 (unless something changed and I'm mistaken now) and my website will convert them based on the size of your table.

The table should not crash into the borders of the table since Marlin has "software endstops" that will limit how far the gantry is allowed to go.

(you might have your X and Y axes flipped?)

**Comment by PDotStrong** [comment]
It should not wrong axis because the center is right from the dimension … hopefully xD

I upload .thr files in the app and export as .thr files from sandify - it works but to small

hmm ok, for my gantry is it possible… dammit

I you the marlin file from your guide. And the homing make what you discribed

**Comment by PDotStrong** [comment]
I didnt change the motherboard value in marlin, could this be the problem? I have a ramps 1.4 board instaed your 1.6 

could that be the readon for my issues with the unbound system an track that are to small?

**Comment by PDotStrong** [comment]
Is it a problem, that I have a rectangle machine configured in sandify and export the file as thr? I found so much points where I dont know what I have to fix, that I got finally a finished table . I hope you can give me hints / guide that I reach my goal :)

**Comment by rdudhagra** [comment]
RAMPS 1.4 should be fine. Can you send me your .thr file and the .gcode file that the server generates when you uploaded the .thr file?

**Comment by rdudhagra** [comment]
If it's not too much work to send them over—might be something about how sandify generates tracks that I'm not aware of.

**Comment by PDotStrong** [comment]
I will create you the files On Monday !

thank you so much for your help! :)
