### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by marcoeli007** [rdudhagra/Sand-Table#44]
Hello, during npm installation get these errors:

npm` ERR! code 1
npm ERR! path /mnt/dietpi_userdata/Website/node_modules/@serialport/bindings
npm ERR! command failed
npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@20.1.0 | linux | arm64
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:456:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:511:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:335:12)
npm ERR! gyp ERR! System Linux 6.1.21-v8+
npm ERR! gyp ERR! command "/usr/local/bin/node" "/mnt/dietpi_userdata/Website/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /mnt/dietpi_userdata/Website/node_modules/@serialport/bindings
npm ERR! gyp ERR! node -v v20.1.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok_

Installation:
- RP3
- Python 3.9.2
- npn 9.6.6
- nvm 0.39.3

Thanks for your help!

**Comment by rdudhagra** [comment]
What version of node do you have installed? It should be `14.8.0`. See https://github.com/rdudhagra/Sand-Table/tree/master/Build%20Guide#raspberry-pi-setupwebserver-installation if you haven't already.

**Comment by marcoeli007** [comment]
Thanks! It works after changing the version. I probably got it mixup during the initial installation...
