### ISSUE TITLE
Bulk Upload (More of a feature request)

### ISSUE THREAD

**Issue by hackintoshlover** [rdudhagra/Sand-Table#50]
Hi Ravi,
Is there a possible way to bulk upload tracks.
I have around .thr files which i manually copied to "files" folder inside the raspberry pi but the website does not load them.
Instead i have to manually upload files one by one using the webpage after which the script converts it to gcode, png and then it is displayed on the webpage.
Any script or shortcut for that.
It's a pain staking process to upload everything one by one.

**Comment by rdudhagra** [comment]
Hey! Unfortunately there's no way to bulk upload right now. However, you can open multiple tabs of the website and upload in parallel (still tedious I guess but overall will take less time).

**Comment by hackintoshlover** [comment]
Guess will settle for manual update for now.
Thanks.
